apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
        name: shivdev
    # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: shivdev
    #       key: course
    # - name: trainer
    #   valueFrom:
    #     configMapKeyRef:
    #       name: shivdev
    #       key: trainer
   

