apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector: # using the selector option to connect the pod wit same labels service create the cluster ip
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port