apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: nginx
  # these labels belongs to replicaset resource
  labels:
    app: nginx
    tier: frontend
spec: 
 # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
# below is pod definition
  templaet:
    metadata:
      labels:
        app: nginx
        tier: frontend
        project: shiv-dev
    spec:
      container:
        name: nginx
        image: nginx