apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-dev
  #these labels are deployment related labels
  labels:
    app: nginx
    purpose: deployment
    tier: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
      project: dev-test
  # these labels are related to pod defination
  template:
    metadata:
      labels:
        app: nginx
        tier: web
        project: dev-test
        extra-key: test
    spec:
      containers:
      - name: nginx
        image: nginx

      